SUNET/multiverse

fabfile/db.py, global/overlay/etc/puppet/cosmos-rules.yaml
because re.search would match on broken regex, nodes that have a part of the name in common with other nodes etc.
=>  Changed from re.search to re.match in db.py

addhost
so that addhost also works on Debian
(also contains another small sync with nunoc-ops).
=> Force pseudo-terminal when running addhost

addhost, global/post-tasks.d/015cosmos-trust
With recent GPG versions, a TTY seems to be required to import keys.
Since importing of keys need to work when running from cron, we
pass --no-tty to those commands. This should mean that -t doesn't
have to be passed to SSH on bootstrapping for new Debian hosts
(tested on Raspbian).
=> gpg import with --no-tty

debian-enable-root.sh, debian-setup.sh, prepare-iaas-debian
* Log in as few times as possible to not require a lot if yubikey keypresses
* Make sure en_US.UTF-8 is present
* Replace `rm -rf` with userdel command
* Make sure the debian account is actually deleted
* Remove locale related warnings when running script from macOS
=> Rework prepare-iaas-debian

addhost, global/overlay/etc/cosmos/apt/bootstrap-cosmos.sh
Before this change there was a need to keep addhost and bootstrap-cosmos.sh in sync regarding what version of the cosmos deb to scp over and later run.
Now we find the latest version as decided by `sort -V` in both addhost and bootstrap-cosmos.sh.
Solution discussed with @fredrikt.
=> Handle multiple versions of cosmos .deb

iaas-setup.sh
For CNaaS machines we supply cloud-init user-data that does not create a default user, in this case the script would exit half-way through. Now it only tries to remove a user if it exists in the first place.
=> iaas-setup.sh: support default user not existing

Makefile
Without this fix:
```
➜  nunoc-ops git:(master) make db
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
make: *** [db] Error 1
```
With this fix:
```
➜  swamid-ops git:(master) ✗ make db
make: Nothing to be done for `db'.
```
Will make it easier to only use `make tag` when to sign changes.
=> Only update the database when needed

global/overlay/etc/cron.d/cosmos, global/overlay/usr/local/bin/run-cosmos, global/overlay/usr/local/libexec/cosmos-cron-wrapper
shellcheck cleanups
move check for no-automatic-cosmos into the wrapper
pass arguments such as -v
run job at reboot too
=> cron wrapper improvements

edit-secrets
We use the separator later on to determine where the yaml document starts. `eyaml edit` adds the separator to new (non-existing) files by itself but since we want to create the file before in order to diff later the separator needs to be added in order to get a valid document.
=> Make sure of separator

global/overlay/etc/puppet/hiera.yaml
And at the same time remove support for gpg.
The modern version of the configuration (v5) has been tested with 20.04 but might work with older dists.
=> Add support for eyaml in Hiera

global/overlay/usr/local/bin/run-cosmos, global/overlay/usr/local/bin/sunet-fleetlock, global/overlay/usr/local/bin/sunet-machine-healthy
Makes run-cosmos request a fleetlock lock before running cosmos "update" and "apply" steps. This is helpful for making sure only one (or several) machine out of some set of machines runs cosmos changes at a time. This way if cosmos (or puppet) decides that a service needs to be restarted this will only happen on a subset of machines at a time. When the cosmos "apply" is done a fleetlock unlock request will be performed so the other machines can progress.
The unlock code in run-cosmos will also run the new tool sunet-machine-healthy to decide things are good before unlocking. This way if a restarted service breaks this will stop the unlock attempt and in turn make it so the others should not break their service as well, giving an operator time to figure out what is wrong.
=> Add fleetlock support to run-cosmos

global/pre-tasks.d/030puppet
This patch will install three packages that is needed for normal operations of puppet using puppet-sunet with multiverse on Debian 12:
cron puppet-module-puppetlabs-cron-core puppet-module-camptocamp-augeas
=> Add additional packages for use with debian 12

bump-tag
This version uses shellchecked modern bash syntax and will allow a new tag to be created
=> A better bump tag

bump-tag
Mariah pointed out that this was lost in:
https://github.com/SUNET/multiverse/commit/6ac9294dea377245ce6947e053da753a9a3b9ba7
And should be reinstated
=>     bump-tag: Compare against current branch

addhost, prepare-iaas-debian, prepare-iaas-ubuntu
With this patch you can specify a ProxyJump for prepare-iaas-ubuntu, prepare-iaas-debian and addhost. Example:
./prepare-iaas-debian 89.47.191.7 hj
./addhost -b -n node1.extern.drive.test.sunet.se -p hj -- 89.47.191.7
where hj is a host defined in my .ssh/config suitable for a proxyjump to the host in question.
This makes it easier to use ip addresses for these scripts which might be neccessary if dns takes a while to propagate.
=> PREPARE/ADDHOST: allow the ues of proxyjump with ip address

global/overlay/etc/systemd/system/run-cosmos-fleetlock-unlocker.service, global/overlay/usr/local/bin/run-cosmos
This extends run-cosmos with a new argument that calls the unlock function already included in the script as well as using the already existing lock() function to make sure there is no race between the bootup process and cron starting a normal run-cosmos process at the same time.
The oexit() function is added to support exiting with a OK exit value the same way eexit() is used to signal something is wrong.
This change also adds the systemd unit file that runs run-cosmos with the new fleetlock-unlock argument at boot if fleetlock is configured.
While here fix indentation that was mixed between 3 and 4 spaces: it is now 4 spaces everywhere.
=> run-cosmos: support fleetlock unlocking at reboot

global/overlay/etc/puppet/cosmos_enc.py
If a host is specified in `cosmos-rules.yaml` with no classes assigned.
=> Allow empty hosts

global/overlay/usr/local/bin/sunet-fleetlock
In order to handle upgrades of the fleetlock server when running only one server we need to handle connection errors like connection refused or timed out errors gracefully.
Because there are several different ways the connection can fail and it is hard to keep track of them all, just catch everything. We then also need special handling of our own timeout execption so we are not accidentally stuck retrying forever.
Also fix so we actually use the request_timeout arg for individual HTTP requests instead of the global timeout.
While here run isort to keep imports tidy.
=> sunet-fleetlock: handle connection errors

global/overlay/etc/puppet/hiera.yaml, global/pre-tasks.d/030puppet
Fixes needed for modern puppet (8.4.0) that is default in ubuntu-24
=> Ubuntu-24 fixes

global/post-tasks.d/010fix-ssh-perms, global/post-tasks.d/014set-cosmos-permissions, global/pre-tasks.d/014set-cosmos-permissions, global/pre-tasks.d/015set-overlay-permissions
This is a merge of various stricter permissions for Cosmos that were identified to be needed when setting up the locked down Tor signing OPS repo to avoid information leakage and possible unauthorized modification by unprivileged users.
The main issue is to restrict access to $COSMOS_BASE at the earliest stage possible to avoid race conditions, during which information could be leaked or modifications made.
Permissions for sensitive files and directories such as /root and /root/.ssh in the overlay are checked separately. A fix is also included to apply the same permission for /root/.ssh/authorized_keys that Puppet applies through sunet::ssh_keys to avoid changing permissions on each run of Cosmos and Puppet.
=> Enforce more strict permissions for files in Cosmos

global/overlay/usr/local/bin/run-cosmos, global/overlay/usr/local/bin/sunet-fleetlock
While we already support setting a healthcheck timeout it probably makes sense to be able to control how long we wait for a fleetlock_lock() or fleetlock_unlock() call. This becomes important if only running cosmos once a night or something like that. In that case we you probably want to give a physical machine more than than 1 minute to complete a reboot etc.
This can now be controlled by setting fleetlock_lock_timeout and fleetlock_unlock_timeout in /etc/run-cosmos-fleetlock-conf. Keep in mind that while it can make sense to increase the time for taking a lock, releasing a lock should always be fast (either you have it and release it, or you dont have it and it is a no-op) so setting a long unlock timeout should probably never be done.
Since we also potentially wait the unlock timeout …
=> fleetlock: configurable lock/unlock timeout

edit-secrets
patch using the same methodology as before when ubuntu22.04 was broken: https://github.com/SUNET/multiverse/commit/a7d0a189da5c4c465aa1f2b60dc8daedab71679b
=> patch for broken eyaml in ubuntu24.04.

global/overlay/usr/local/bin/run-cosmos
While the run-cosmos script in cnaas-ops looks very different from what is currently in multiverse this brings in "set -e" and "--random-sleep" support which was missing from the multiverse version.
=> Add functionality from cnaas-ops

global/overlay/usr/local/libexec/cosmos-cron-wrapper
Now that run-cosmos in multiverse understands --random-sleep, use it in the cron wrapper to make machines spread out the load.
=> cosmos-cron-wrapper: Add '--random-sleep'

addhost
Från noc@sunet.se:
Hej!
Hittade ett par buggar i SUNET/multiverse/addhost och det verkar inte gå att skapa en issue, så jag mailar er istället. Den ena är ett resultat av commit “7323626” där Fredrik Thulin bytte ut getopt mot getopts getopts gillar inte shiftoperationer i while-loopen och genom att använda det i hanteringen av -n så äts nästa argument upp av shiftoperationen. Nästa bugg kom i commit “71e112e” av Micke Nordin. Den kopierar dels samma fel med shift, men har också tappat ett “:” i argumentlistan till getopts vilket gör att -n inte längre tar ett argument Här är några exempel på fel (Jag har skjutit in följande kod på rad 44 för att debugga) echo "cmd_hostname = $cmd_hostname"
echo "cmd_do_bootstrap = $cmd_do_bootstrap"
echo "cmd_fqdn = $cmd_fqdn"
echo "cmd_proxy = …
=> Fix: getopts

global/post-tasks.d/015cosmos-trust
* Before this the tool would not try to re-import a key file unless the key was expired, but if that key was also the one that signed the ops-repo this would never happen as the key would expire and update.d/25verify-git would prevent this script from running. Now we always import files if the contained key is not expired so we will read in updated files before they expire.
* Only import a key file if it includes a single pubkey. Before this the code seems to have accepted files with multiple keys yet the fingerprint parsing only found the first fingerprint so it would clean up additional keys on follow-up runs as it considered the additional fingerprints missing.
* Fix SEEN check that aborted the tool if no keys at all have been seen. The previous check probably never worked.
* Fix code …
=> Multiple fixes to 015cosmos-trust
